version: '2'

services:
  node:
    build: .docker/node
    volumes:
      - ./app:/var/www
    ports:
      - 8088:8080
#    volumes:
#      - ./:/var/www/dev
#      - ./.docker/nginx/conf.d:/etc/nginx/conf.d/
